name: as-tests
on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  as-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install and init
        run: npm install && npm init && npm install --save-dec assemblyscript && npx asinit .
      - name: run test 
        run: npm run asbuild && npm test && npm start
